### ISSUE TITLE
vscode: how to disable fa4/fa5/fa5p/@fa5p snnipet suggestion?

### ISSUE THREAD

**Issue by XuanChuYun** [1tontech/bootstrap4-snippets#28]
I just want a code suggestion for b4, No code hints for font ICONS. Thanks for a great god

**Comment by codeThaGlobe** [comment]
Yes. These compete with more relevant snippets very frequently as they are many and are at top of list.

**Comment by dairan** [comment]
unfortunately, I stopped to use this plugin because this icon feature :\

**Comment by Garri7** [comment]
Disable bootstrap extension
